"""Add table_id to game_session

Revision ID: 0007
Revises: 0006
Create Date: 2025-03-30 23:14:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006_add_blackjack_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_game_session_table_id_blackjack_table', # Constraint name
            'blackjack_table', ['table_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_session_table_id_blackjack_table', type_='foreignkey')
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###