"""Add game_type to game_session

Revision ID: 0008
Revises: 0007
Create Date: 2025-03-30 23:15:30.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        # Add the column, initially nullable to allow setting default
        batch_op.add_column(sa.Column('game_type', sa.String(length=50), nullable=True))

    # Update existing rows to have a default game_type (assuming 'slot')
    op.execute("UPDATE game_session SET game_type = 'slot' WHERE game_type IS NULL")

    # Alter the column to be non-nullable
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('game_type', existing_type=sa.String(length=50), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_column('game_type')

    # ### end Alembic commands ###