"""add_spacecrash_game_and_bet_models

Revision ID: 0b7dbac9fd44
Revises: 93adbc7a66aa
Create Date: 2025-06-02 20:27:08.785181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7dbac9fd44'
down_revision = '4a5d8e2197b3' # Was 93adbc7a66aa, which is now merged by 4a5d8e2197b3
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spacecrash_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_seed', sa.String(length=255), nullable=False),
    sa.Column('client_seed', sa.String(length=255), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('crash_point', sa.Float(), nullable=True),
    sa.Column('public_seed', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('game_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spacecrash_game_status'), 'spacecrash_game', ['status'], unique=False)
    op.create_table('spacecrash_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.BigInteger(), nullable=False),
    sa.Column('auto_eject_at', sa.Float(), nullable=True),
    sa.Column('ejected_at', sa.Float(), nullable=True),
    sa.Column('win_amount', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['spacecrash_game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spacecrash_bet_game_id'), 'spacecrash_bet', ['game_id'], unique=False)
    op.create_index(op.f('ix_spacecrash_bet_status'), 'spacecrash_bet', ['status'], unique=False)
    op.create_index(op.f('ix_spacecrash_bet_user_id'), 'spacecrash_bet', ['user_id'], unique=False)
    op.create_table('user_bonus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bonus_code_id', sa.Integer(), nullable=False),
    sa.Column('bonus_amount_awarded_sats', sa.BigInteger(), nullable=False),
    sa.Column('wagering_requirement_multiplier', sa.Float(), nullable=True),
    sa.Column('wagering_requirement_sats', sa.BigInteger(), nullable=False),
    sa.Column('wagering_progress_sats', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bonus_code_id'], ['bonus_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bonus_bonus_code_id'), 'user_bonus', ['bonus_code_id'], unique=False)
    op.create_index(op.f('ix_user_bonus_is_active'), 'user_bonus', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_bonus_is_cancelled'), 'user_bonus', ['is_cancelled'], unique=False)
    op.create_index(op.f('ix_user_bonus_is_completed'), 'user_bonus', ['is_completed'], unique=False)
    op.create_index(op.f('ix_user_bonus_user_id'), 'user_bonus', ['user_id'], unique=False)
    
    with op.batch_alter_table('bonus_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_sats', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('wagering_requirement_multiplier', sa.Float(), nullable=True))
        batch_op.alter_column('amount',
                   existing_type=sa.FLOAT(),
                   nullable=True)
        batch_op.create_index(op.f('ix_bonus_code_code_id'), ['code_id'], unique=True)

    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.drop_column('scatter_symbol_id')
        batch_op.drop_column('wild_symbol_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(op.f('ix_user_username'), ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_user_username'))
        batch_op.drop_index(op.f('ix_user_email'))

    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wild_symbol_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('scatter_symbol_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('bonus_code', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_bonus_code_code_id'))
        batch_op.alter_column('amount',
                   existing_type=sa.FLOAT(),
                   nullable=False)
        batch_op.drop_column('wagering_requirement_multiplier')
        batch_op.drop_column('amount_sats')

    op.drop_index(op.f('ix_user_bonus_user_id'), table_name='user_bonus')
    op.drop_index(op.f('ix_user_bonus_is_completed'), table_name='user_bonus')
    op.drop_index(op.f('ix_user_bonus_is_cancelled'), table_name='user_bonus')
    op.drop_index(op.f('ix_user_bonus_is_active'), table_name='user_bonus')
    op.drop_index(op.f('ix_user_bonus_bonus_code_id'), table_name='user_bonus')
    op.drop_table('user_bonus')
    op.drop_index(op.f('ix_spacecrash_bet_user_id'), table_name='spacecrash_bet')
    op.drop_index(op.f('ix_spacecrash_bet_status'), table_name='spacecrash_bet')
    op.drop_index(op.f('ix_spacecrash_bet_game_id'), table_name='spacecrash_bet')
    op.drop_table('spacecrash_bet')
    op.drop_index(op.f('ix_spacecrash_game_status'), table_name='spacecrash_game')
    op.drop_table('spacecrash_game')
    # ### end Alembic commands ###
