"""add_crystal_garden_models

Revision ID: add_crystal_garden_models
Revises: fix_slot_configs
Create Date: 2025-06-15 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_crystal_garden_models'
down_revision = 'fix_slot_configs' # From 20250608000001_fix_slot_configurations.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crystal_seed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('potential_outcomes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_garden',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grid_size_x', sa.Integer(), nullable=False, server_default='5'),
    sa.Column('grid_size_y', sa.Integer(), nullable=False, server_default='5'),
    sa.Column('last_cycle_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('crystal_flower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crystal_seed_id', sa.Integer(), nullable=False),
    sa.Column('player_garden_id', sa.Integer(), nullable=False),
    sa.Column('planted_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('growth_stage', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('clarity', sa.Float(), nullable=True),
    sa.Column('special_type', sa.String(length=100), nullable=True),
    sa.Column('appraised_value', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crystal_seed_id'], ['crystal_seed.id'], ),
    sa.ForeignKeyConstraint(['player_garden_id'], ['player_garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crystal_codex_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crystal_name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('clarity', sa.Float(), nullable=False),
    sa.Column('special_type', sa.String(length=100), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crystal_codex_entry')
    op.drop_table('crystal_flower')
    op.drop_table('player_garden')
    op.drop_table('crystal_seed')
    # ### end Alembic commands ###
