"""add_astrominerx_models

Revision ID: 20250619115445
Revises: 20250615010000
Create Date: 2025-06-19 11:54:45.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250619115445'
down_revision = '20250615010000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astro_miner_x_expedition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_value_collected', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_astro_miner_x_expedition_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_astro_miner_x_expedition'))
    )
    with op.batch_alter_table('astro_miner_x_expedition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_astro_miner_x_expedition_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_astro_miner_x_expedition_user_id'), ['user_id'], unique=False)

    op.create_table('astro_miner_x_asteroid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('asteroid_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_empty', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_hazard', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scan_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expedition_id'], ['astro_miner_x_expedition.id'], name=op.f('fk_astro_miner_x_asteroid_expedition_id_astro_miner_x_expedition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_astro_miner_x_asteroid'))
    )
    with op.batch_alter_table('astro_miner_x_asteroid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_astro_miner_x_asteroid_expedition_id'), ['expedition_id'], unique=False)

    op.create_table('astro_miner_x_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('collected_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['astro_miner_x_expedition.id'], name=op.f('fk_astro_miner_x_resource_expedition_id_astro_miner_x_expedition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_astro_miner_x_resource'))
    )
    with op.batch_alter_table('astro_miner_x_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_astro_miner_x_resource_expedition_id'), ['expedition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('astro_miner_x_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_astro_miner_x_resource_expedition_id'))
    op.drop_table('astro_miner_x_resource')

    with op.batch_alter_table('astro_miner_x_asteroid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_astro_miner_x_asteroid_expedition_id'))
    op.drop_table('astro_miner_x_asteroid')

    with op.batch_alter_table('astro_miner_x_expedition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_astro_miner_x_expedition_user_id'))
        batch_op.drop_index(batch_op.f('ix_astro_miner_x_expedition_status'))
    op.drop_table('astro_miner_x_expedition')
    # ### end Alembic commands ###
