"""add betting_start_time to spacecrash_game

Revision ID: 8fa28c7146ce
Revises: cdf792cd43c4
Create Date: 2025-06-18 23:04:06.984549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa28c7146ce'
down_revision = 'cdf792cd43c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baccarat_action', schema=None) as batch_op:
        batch_op.drop_constraint('baccarat_action_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('baccarat_action_baccarat_hand_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'baccarat_hand', ['baccarat_hand_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('baccarat_hand', schema=None) as batch_op:
        batch_op.drop_constraint('baccarat_hand_game_session_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('baccarat_hand_table_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('baccarat_hand_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'baccarat_table', ['table_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'game_session', ['game_session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('blackjack_action', schema=None) as batch_op:
        batch_op.drop_constraint('blackjack_action_hand_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'blackjack_hand', ['hand_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('blackjack_hand', schema=None) as batch_op:
        batch_op.drop_constraint('blackjack_hand_session_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('blackjack_hand_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('blackjack_hand_table_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'game_session', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'blackjack_table', ['table_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('bonus_code', schema=None) as batch_op:
        batch_op.drop_constraint('bonus_code_code_id_key', type_='unique')
        batch_op.drop_index('ix_bonus_code_code_id')
        batch_op.create_index(batch_op.f('ix_bonus_code_code_id'), ['code_id'], unique=True)

    with op.batch_alter_table('crystal_codex_entry', schema=None) as batch_op:
        batch_op.drop_constraint('crystal_codex_entry_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('crystal_flower', schema=None) as batch_op:
        batch_op.drop_constraint('crystal_flower_player_garden_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('crystal_flower_crystal_seed_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('crystal_flower_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'player_garden', ['player_garden_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'crystal_seed', ['crystal_seed_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_constraint('game_session_table_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('game_session_baccarat_table_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('game_session_slot_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('game_session_poker_table_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('game_session_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'poker_table', ['poker_table_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'slot', ['slot_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'blackjack_table', ['table_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'baccarat_table', ['baccarat_table_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('player_garden', schema=None) as batch_op:
        batch_op.drop_constraint('player_garden_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('plinko_drop_log', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.drop_constraint('plinko_drop_log_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('poker_hand', schema=None) as batch_op:
        batch_op.drop_constraint('poker_hand_last_raiser_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('poker_hand_table_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('poker_hand_current_turn_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'poker_table', ['table_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['last_raiser_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['current_turn_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poker_player_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poker_player_state_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poker_player_state_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('poker_player_state_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('poker_player_state_table_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'poker_table', ['table_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('roulette_game', schema=None) as batch_op:
        batch_op.alter_column('bet_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('payout',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.drop_constraint('roulette_game_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('slot_bet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_bet_slot_id'), ['slot_id'], unique=False)
        batch_op.drop_constraint('slot_bet_slot_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'slot', ['slot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('slot_spin', schema=None) as batch_op:
        batch_op.drop_constraint('slot_spin_game_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'game_session', ['game_session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('slot_symbol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_symbol_slot_id'), ['slot_id'], unique=False)
        batch_op.drop_constraint('slot_symbol_slot_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'slot', ['slot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('spacecrash_bet', schema=None) as batch_op:
        batch_op.drop_constraint('spacecrash_bet_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('spacecrash_bet_game_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'spacecrash_game', ['game_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('spacecrash_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betting_start_time', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_constraint('token_blacklist_jti_key', type_='unique')
        batch_op.drop_index('ix_token_blacklist_jti')
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_transaction_baccarat_hand_id'), ['baccarat_hand_id'], unique=False)
        batch_op.drop_constraint('transaction_poker_hand_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transaction_slot_spin_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transaction_plinko_drop_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transaction_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transaction_baccarat_hand_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transaction_blackjack_hand_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'baccarat_hand', ['baccarat_hand_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'blackjack_hand', ['blackjack_hand_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'plinko_drop_log', ['plinko_drop_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'poker_hand', ['poker_hand_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'slot_spin', ['slot_spin_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_wallet_private_key', sa.Text(), nullable=True))
        batch_op.drop_constraint('user_deposit_wallet_address_key', type_='unique')
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_index('ix_user_deposit_wallet_address')
        batch_op.create_index(batch_op.f('ix_user_deposit_wallet_address'), ['deposit_wallet_address'], unique=True)
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('user_bonus', schema=None) as batch_op:
        batch_op.drop_constraint('user_bonus_bonus_code_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_bonus_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'bonus_code', ['bonus_code_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bonus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_bonus_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_bonus_bonus_code_id_fkey', 'bonus_code', ['bonus_code_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_deposit_wallet_address'))
        batch_op.create_index('ix_user_deposit_wallet_address', ['deposit_wallet_address'], unique=False)
        batch_op.create_unique_constraint('user_username_key', ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('user_email_key', ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('user_deposit_wallet_address_key', ['deposit_wallet_address'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('deposit_wallet_private_key')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_blackjack_hand_id_fkey', 'blackjack_hand', ['blackjack_hand_id'], ['id'])
        batch_op.create_foreign_key('transaction_baccarat_hand_id_fkey', 'baccarat_hand', ['baccarat_hand_id'], ['id'])
        batch_op.create_foreign_key('transaction_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('transaction_plinko_drop_id_fkey', 'plinko_drop_log', ['plinko_drop_id'], ['id'])
        batch_op.create_foreign_key('transaction_slot_spin_id_fkey', 'slot_spin', ['slot_spin_id'], ['id'])
        batch_op.create_foreign_key('transaction_poker_hand_id_fkey', 'poker_hand', ['poker_hand_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_transaction_baccarat_hand_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))
        batch_op.create_index('ix_token_blacklist_jti', ['jti'], unique=False)
        batch_op.create_unique_constraint('token_blacklist_jti_key', ['jti'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('spacecrash_game', schema=None) as batch_op:
        batch_op.drop_column('betting_start_time')

    with op.batch_alter_table('spacecrash_bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('spacecrash_bet_game_id_fkey', 'spacecrash_game', ['game_id'], ['id'])
        batch_op.create_foreign_key('spacecrash_bet_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('slot_symbol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('slot_symbol_slot_id_fkey', 'slot', ['slot_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_slot_symbol_slot_id'))

    with op.batch_alter_table('slot_spin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('slot_spin_game_session_id_fkey', 'game_session', ['game_session_id'], ['id'])

    with op.batch_alter_table('slot_bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('slot_bet_slot_id_fkey', 'slot', ['slot_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_slot_bet_slot_id'))

    with op.batch_alter_table('roulette_game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roulette_game_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('payout',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('bet_amount',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('poker_player_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('poker_player_state_table_id_fkey', 'poker_table', ['table_id'], ['id'])
        batch_op.create_foreign_key('poker_player_state_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_poker_player_state_user_id'))
        batch_op.drop_index(batch_op.f('ix_poker_player_state_table_id'))

    with op.batch_alter_table('poker_hand', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('poker_hand_current_turn_user_id_fkey', 'user', ['current_turn_user_id'], ['id'])
        batch_op.create_foreign_key('poker_hand_table_id_fkey', 'poker_table', ['table_id'], ['id'])
        batch_op.create_foreign_key('poker_hand_last_raiser_user_id_fkey', 'user', ['last_raiser_user_id'], ['id'])

    with op.batch_alter_table('plinko_drop_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('plinko_drop_log_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('player_garden', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('player_garden_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('game_session_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('game_session_poker_table_id_fkey', 'poker_table', ['poker_table_id'], ['id'])
        batch_op.create_foreign_key('game_session_slot_id_fkey', 'slot', ['slot_id'], ['id'])
        batch_op.create_foreign_key('game_session_baccarat_table_id_fkey', 'baccarat_table', ['baccarat_table_id'], ['id'])
        batch_op.create_foreign_key('game_session_table_id_fkey', 'blackjack_table', ['table_id'], ['id'])

    with op.batch_alter_table('crystal_flower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('crystal_flower_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('crystal_flower_crystal_seed_id_fkey', 'crystal_seed', ['crystal_seed_id'], ['id'])
        batch_op.create_foreign_key('crystal_flower_player_garden_id_fkey', 'player_garden', ['player_garden_id'], ['id'])

    with op.batch_alter_table('crystal_codex_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('crystal_codex_entry_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('bonus_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonus_code_code_id'))
        batch_op.create_index('ix_bonus_code_code_id', ['code_id'], unique=False)
        batch_op.create_unique_constraint('bonus_code_code_id_key', ['code_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('blackjack_hand', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blackjack_hand_table_id_fkey', 'blackjack_table', ['table_id'], ['id'])
        batch_op.create_foreign_key('blackjack_hand_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('blackjack_hand_session_id_fkey', 'game_session', ['session_id'], ['id'])

    with op.batch_alter_table('blackjack_action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blackjack_action_hand_id_fkey', 'blackjack_hand', ['hand_id'], ['id'])

    with op.batch_alter_table('baccarat_hand', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('baccarat_hand_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('baccarat_hand_table_id_fkey', 'baccarat_table', ['table_id'], ['id'])
        batch_op.create_foreign_key('baccarat_hand_game_session_id_fkey', 'game_session', ['game_session_id'], ['id'])

    with op.batch_alter_table('baccarat_action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('baccarat_action_baccarat_hand_id_fkey', 'baccarat_hand', ['baccarat_hand_id'], ['id'])
        batch_op.create_foreign_key('baccarat_action_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
