"""Add slot_spin_id and blackjack_hand_id to Transaction model

Revision ID: 93adbc7a66aa
Revises: e19c416cd61b
Create Date: 2025-06-01 04:43:05.771663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93adbc7a66aa'
down_revision = 'e19c416cd61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('slot_spin_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('blackjack_hand_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transaction_blackjack_hand_id'), 'transaction', ['blackjack_hand_id'], unique=False)
    op.create_index(op.f('ix_transaction_slot_spin_id'), 'transaction', ['slot_spin_id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'slot_spin', ['slot_spin_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'blackjack_hand', ['blackjack_hand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_slot_spin_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_blackjack_hand_id'), table_name='transaction')
    op.drop_column('transaction', 'blackjack_hand_id')
    op.drop_column('transaction', 'slot_spin_id')
    # ### end Alembic commands ###
