"""Add slot_spin_id and blackjack_hand_id to Transaction model

Revision ID: 93adbc7a66aa
Revises: e19c416cd61b
Create Date: 2025-06-01 04:43:05.771663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93adbc7a66aa'
down_revision = 'e19c416cd61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_spin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blackjack_hand_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_transaction_blackjack_hand_id'), ['blackjack_hand_id'], unique=False)
        batch_op.create_index(op.f('ix_transaction_slot_spin_id'), ['slot_spin_id'], unique=False)
        batch_op.create_foreign_key('fk_transaction_slot_spin_id', 'slot_spin', ['slot_spin_id'], ['id'])
        batch_op.create_foreign_key('fk_transaction_blackjack_hand_id', 'blackjack_hand', ['blackjack_hand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_blackjack_hand_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transaction_slot_spin_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_transaction_slot_spin_id'))
        batch_op.drop_index(op.f('ix_transaction_blackjack_hand_id'))
        batch_op.drop_column('blackjack_hand_id')
        batch_op.drop_column('slot_spin_id')
    # ### end Alembic commands ###
