"""initial migration from current models

Revision ID: b57bf8ca2042
Revises: 
Create Date: 2025-06-02 20:27:37.874660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57bf8ca2042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackjack_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('min_bet', sa.BigInteger(), nullable=False),
    sa.Column('max_bet', sa.BigInteger(), nullable=False),
    sa.Column('deck_count', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amount_sats', sa.BigInteger(), nullable=True),
    sa.Column('wagering_requirement_multiplier', sa.Float(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_remaining', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_code_code_id'), 'bonus_code', ['code_id'], unique=True)
    op.create_index(op.f('ix_bonus_code_is_active'), 'bonus_code', ['is_active'], unique=False)
    op.create_table('poker_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('limit_type', sa.String(length=50), nullable=False),
    sa.Column('small_blind', sa.BigInteger(), nullable=False),
    sa.Column('big_blind', sa.BigInteger(), nullable=False),
    sa.Column('min_buy_in', sa.BigInteger(), nullable=False),
    sa.Column('max_buy_in', sa.BigInteger(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poker_table_is_active'), 'poker_table', ['is_active'], unique=False)
    op.create_table('slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('num_rows', sa.Integer(), nullable=False),
    sa.Column('num_columns', sa.Integer(), nullable=False),
    sa.Column('num_symbols', sa.Integer(), nullable=False),
    sa.Column('bonus_type', sa.String(length=50), nullable=True),
    sa.Column('bonus_subtype', sa.String(length=50), nullable=True),
    sa.Column('bonus_multiplier', sa.Float(), nullable=False),
    sa.Column('bonus_spins_trigger_count', sa.Integer(), nullable=False),
    sa.Column('bonus_spins_awarded', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('asset_directory', sa.String(length=100), nullable=False),
    sa.Column('rtp', sa.Float(), nullable=True),
    sa.Column('volatility', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_index(op.f('ix_slot_is_active'), 'slot', ['is_active'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('deposit_wallet_address', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deposit_wallet_address')
    )
    op.create_index(op.f('ix_user_balance'), 'user', ['balance'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('bonus_active', sa.Boolean(), nullable=False),
    sa.Column('bonus_spins_remaining', sa.Integer(), nullable=False),
    sa.Column('bonus_multiplier', sa.Float(), nullable=False),
    sa.Column('amount_wagered', sa.BigInteger(), nullable=False),
    sa.Column('amount_won', sa.BigInteger(), nullable=False),
    sa.Column('num_spins', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['blackjack_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_session_session_end'), 'game_session', ['session_end'], unique=False)
    op.create_index(op.f('ix_game_session_slot_id'), 'game_session', ['slot_id'], unique=False)
    op.create_index(op.f('ix_game_session_table_id'), 'game_session', ['table_id'], unique=False)
    op.create_index(op.f('ix_game_session_user_id'), 'game_session', ['user_id'], unique=False)
    op.create_table('poker_hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('hand_history', sa.JSON(), nullable=False),
    sa.Column('board_cards', sa.JSON(), nullable=True),
    sa.Column('pot_size_sats', sa.BigInteger(), nullable=False),
    sa.Column('rake_sats', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winners', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['poker_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poker_hand_start_time'), 'poker_hand', ['start_time'], unique=False)
    op.create_index(op.f('ix_poker_hand_table_id'), 'poker_hand', ['table_id'], unique=False)
    op.create_table('poker_player_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('stack_sats', sa.BigInteger(), nullable=False),
    sa.Column('is_sitting_out', sa.Boolean(), nullable=False),
    sa.Column('is_active_in_hand', sa.Boolean(), nullable=False),
    sa.Column('hole_cards', sa.JSON(), nullable=True),
    sa.Column('last_action', sa.String(length=50), nullable=True),
    sa.Column('time_to_act_ends', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['poker_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'seat_id', name='uq_table_seat'),
    sa.UniqueConstraint('user_id', 'table_id', name='uq_user_table')
    )
    op.create_index(op.f('ix_poker_player_state_table_id'), 'poker_player_state', ['table_id'], unique=False)
    op.create_index(op.f('ix_poker_player_state_user_id'), 'poker_player_state', ['user_id'], unique=False)
    op.create_index('ix_poker_player_state_user_table_seat', 'poker_player_state', ['user_id', 'table_id', 'seat_id'], unique=False)
    op.create_table('slot_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_bet_slot_id'), 'slot_bet', ['slot_id'], unique=False)
    op.create_index('ix_slot_bet_slot_id_bet_amount', 'slot_bet', ['slot_id', 'bet_amount'], unique=True)
    op.create_table('slot_symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('symbol_internal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('img_link', sa.String(length=256), nullable=False),
    sa.Column('value_multiplier', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_symbol_slot_id'), 'slot_symbol', ['slot_id'], unique=False)
    op.create_index('ix_slot_symbol_slot_id_internal_id', 'slot_symbol', ['slot_id', 'symbol_internal_id'], unique=True)
    op.create_table('user_bonus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bonus_code_id', sa.Integer(), nullable=False),
    sa.Column('bonus_amount_awarded_sats', sa.BigInteger(), nullable=False),
    sa.Column('wagering_requirement_multiplier', sa.Float(), nullable=True),
    sa.Column('wagering_requirement_sats', sa.BigInteger(), nullable=False),
    sa.Column('wagering_progress_sats', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bonus_code_id'], ['bonus_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bonus_bonus_code_id'), 'user_bonus', ['bonus_code_id'], unique=False)
    op.create_index(op.f('ix_user_bonus_is_active'), 'user_bonus', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_bonus_is_cancelled'), 'user_bonus', ['is_cancelled'], unique=False)
    op.create_index(op.f('ix_user_bonus_is_completed'), 'user_bonus', ['is_completed'], unique=False)
    op.create_index(op.f('ix_user_bonus_user_id'), 'user_bonus', ['user_id'], unique=False)
    op.create_table('blackjack_hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('initial_bet', sa.BigInteger(), nullable=False),
    sa.Column('total_bet', sa.BigInteger(), nullable=False),
    sa.Column('win_amount', sa.BigInteger(), nullable=True),
    sa.Column('player_cards', sa.JSON(), nullable=False),
    sa.Column('dealer_cards', sa.JSON(), nullable=False),
    sa.Column('player_hands', sa.JSON(), nullable=False),
    sa.Column('dealer_hand', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_session.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['blackjack_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackjack_hand_session_id'), 'blackjack_hand', ['session_id'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_status'), 'blackjack_hand', ['status'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_table_id'), 'blackjack_hand', ['table_id'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_user_id'), 'blackjack_hand', ['user_id'], unique=False)
    op.create_table('slot_spin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('spin_result', sa.JSON(), nullable=False),
    sa.Column('win_amount', sa.BigInteger(), nullable=False),
    sa.Column('bet_amount', sa.BigInteger(), nullable=False),
    sa.Column('is_bonus_spin', sa.Boolean(), nullable=False),
    sa.Column('spin_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_spin_game_session_id'), 'slot_spin', ['game_session_id'], unique=False)
    op.create_index(op.f('ix_slot_spin_spin_time'), 'slot_spin', ['spin_time'], unique=False)
    op.create_table('blackjack_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('hand_index', sa.Integer(), nullable=False),
    sa.Column('card_dealt', sa.JSON(), nullable=True),
    sa.Column('hand_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['blackjack_hand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackjack_action_hand_id'), 'blackjack_action', ['hand_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_spin_id', sa.Integer(), nullable=True),
    sa.Column('blackjack_hand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blackjack_hand_id'], ['blackjack_hand.id'], ),
    sa.ForeignKeyConstraint(['slot_spin_id'], ['slot_spin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_blackjack_hand_id'), 'transaction', ['blackjack_hand_id'], unique=False)
    op.create_index(op.f('ix_transaction_created_at'), 'transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_slot_spin_id'), 'transaction', ['slot_spin_id'], unique=False)
    op.create_index(op.f('ix_transaction_status'), 'transaction', ['status'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_type'), 'transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_transaction_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_status'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_slot_spin_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_created_at'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_blackjack_hand_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_blackjack_action_hand_id'), table_name='blackjack_action')
    op.drop_table('blackjack_action')
    op.drop_index(op.f('ix_slot_spin_spin_time'), table_name='slot_spin')
    op.drop_index(op.f('ix_slot_spin_game_session_id'), table_name='slot_spin')
    op.drop_table('slot_spin')
    op.drop_index(op.f('ix_blackjack_hand_user_id'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_table_id'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_status'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_session_id'), table_name='blackjack_hand')
    op.drop_table('blackjack_hand')
    op.drop_index(op.f('ix_user_bonus_user_id'), table_name='user_bonus')
    op.drop_index(op.f('ix_user_bonus_is_completed'), table_name='user_bonus')
    op.drop_index(op.f('ix_user_bonus_is_cancelled'), table_name='user_bonus')
    op.drop_index(op.f('ix_user_bonus_is_active'), table_name='user_bonus')
    op.drop_index(op.f('ix_user_bonus_bonus_code_id'), table_name='user_bonus')
    op.drop_table('user_bonus')
    op.drop_index('ix_slot_symbol_slot_id_internal_id', table_name='slot_symbol')
    op.drop_index(op.f('ix_slot_symbol_slot_id'), table_name='slot_symbol')
    op.drop_table('slot_symbol')
    op.drop_index('ix_slot_bet_slot_id_bet_amount', table_name='slot_bet')
    op.drop_index(op.f('ix_slot_bet_slot_id'), table_name='slot_bet')
    op.drop_table('slot_bet')
    op.drop_index('ix_poker_player_state_user_table_seat', table_name='poker_player_state')
    op.drop_index(op.f('ix_poker_player_state_user_id'), table_name='poker_player_state')
    op.drop_index(op.f('ix_poker_player_state_table_id'), table_name='poker_player_state')
    op.drop_table('poker_player_state')
    op.drop_index(op.f('ix_poker_hand_table_id'), table_name='poker_hand')
    op.drop_index(op.f('ix_poker_hand_start_time'), table_name='poker_hand')
    op.drop_table('poker_hand')
    op.drop_index(op.f('ix_game_session_user_id'), table_name='game_session')
    op.drop_index(op.f('ix_game_session_table_id'), table_name='game_session')
    op.drop_index(op.f('ix_game_session_slot_id'), table_name='game_session')
    op.drop_index(op.f('ix_game_session_session_end'), table_name='game_session')
    op.drop_table('game_session')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_balance'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_slot_is_active'), table_name='slot')
    op.drop_table('slot')
    op.drop_index(op.f('ix_poker_table_is_active'), table_name='poker_table')
    op.drop_table('poker_table')
    op.drop_index(op.f('ix_bonus_code_is_active'), table_name='bonus_code')
    op.drop_index(op.f('ix_bonus_code_code_id'), table_name='bonus_code')
    op.drop_table('bonus_code')
    op.drop_table('blackjack_table')
    # ### end Alembic commands ###
