"""Remove deposit_wallet_private_key from User model

Revision ID: e19c416cd61b
Revises: 78886037bd7f
Create Date: 2025-06-01 04:41:57.917390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19c416cd61b'
down_revision = '78886037bd7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blackjack_action_hand_id'), 'blackjack_action', ['hand_id'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_session_id'), 'blackjack_hand', ['session_id'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_status'), 'blackjack_hand', ['status'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_table_id'), 'blackjack_hand', ['table_id'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_user_id'), 'blackjack_hand', ['user_id'], unique=False)
    
    with op.batch_alter_table('bonus_code', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_bonus_code_code_id')) # Drop the unique index instead

    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('slot_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('game_type',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=20),
                              existing_nullable=False)
        batch_op.create_index(op.f('ix_game_session_table_id'), ['table_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_user_email'))
        batch_op.drop_index(op.f('ix_user_username'))
        batch_op.drop_column('deposit_wallet_private_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_wallet_private_key', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        # Assuming the unnamed UniqueConstraint('email') and UniqueConstraint('username') from 0001 are implicitly recreated by SQLite if not explicitly handled.
        # Or, if these specific named indexes are critical:
        batch_op.create_index(op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_index(op.f('ix_user_email'), ['email'], unique=True)


    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_game_session_table_id'))
        batch_op.alter_column('game_type',
                              existing_type=sa.String(length=20),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=False)
        batch_op.alter_column('slot_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    with op.batch_alter_table('bonus_code', schema=None) as batch_op:
        batch_op.create_index(op.f('ix_bonus_code_code_id'), ['code_id'], unique=True) # Recreate the index

    op.drop_index(op.f('ix_blackjack_hand_user_id'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_table_id'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_status'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_session_id'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_action_hand_id'), table_name='blackjack_action')
    # ### end Alembic commands ###
