"""Remove deposit_wallet_private_key from User model

Revision ID: e19c416cd61b
Revises: 78886037bd7f
Create Date: 2025-06-01 04:41:57.917390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19c416cd61b'
down_revision = '78886037bd7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blackjack_action_hand_id'), 'blackjack_action', ['hand_id'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_session_id'), 'blackjack_hand', ['session_id'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_status'), 'blackjack_hand', ['status'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_table_id'), 'blackjack_hand', ['table_id'], unique=False)
    op.create_index(op.f('ix_blackjack_hand_user_id'), 'blackjack_hand', ['user_id'], unique=False)
    op.drop_constraint(op.f('bonus_code_code_id_key'), 'bonus_code', type_='unique')
    op.alter_column('game_session', 'slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_session', 'game_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_game_session_table_id'), 'game_session', ['table_id'], unique=False)
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.drop_column('user', 'deposit_wallet_private_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deposit_wallet_private_key', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_game_session_table_id'), table_name='game_session')
    op.alter_column('game_session', 'game_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('game_session', 'slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(op.f('bonus_code_code_id_key'), 'bonus_code', ['code_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_blackjack_hand_user_id'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_table_id'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_status'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_hand_session_id'), table_name='blackjack_hand')
    op.drop_index(op.f('ix_blackjack_action_hand_id'), table_name='blackjack_action')
    # ### end Alembic commands ###
