"""Add PlinkoDropLog table and plinko_drop_id to Transaction

Revision ID: plinko_features_manual
Revises: 4a5d8e2197b3
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from alembic import op
import sqlalchemy as sa
# No specific dialect imports like postgresql.JSONB should be needed if using generic types.

# revision identifiers, used by Alembic.
revision = 'plinko_features_manual'
down_revision = '4a5d8e2197b3' # The merge commit created earlier
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually generated based on model changes for Plinko

    # Create plinko_drop_log table
    op.create_table('plinko_drop_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stake_amount', sa.BigInteger(), nullable=False),
    sa.Column('chosen_stake_label', sa.String(length=50), nullable=False),
    sa.Column('slot_landed_label', sa.String(length=50), nullable=False),
    sa.Column('multiplier_applied', sa.Float(), nullable=False),
    sa.Column('winnings_amount', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plinko_drop_log_timestamp'), 'plinko_drop_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_plinko_drop_log_user_id'), 'plinko_drop_log', ['user_id'], unique=False)
    print("Created 'plinko_drop_log' table and its indexes.")

    # Add plinko_drop_id column to transaction table
    op.add_column('transaction', sa.Column('plinko_drop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transaction_plinko_drop_id'), 'transaction', ['plinko_drop_id'], unique=False)
    op.create_foreign_key(
        'fk_transaction_plinko_drop_id_plinko_drop_log', # Constraint name
        'transaction', 'plinko_drop_log',
        ['plinko_drop_id'], ['id']
    )
    print("Added 'plinko_drop_id' to 'transaction' table with index and foreign key.")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually generated based on model changes for Plinko

    op.drop_constraint('fk_transaction_plinko_drop_id_plinko_drop_log', 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_plinko_drop_id'), table_name='transaction')
    op.drop_column('transaction', 'plinko_drop_id')
    print("Dropped 'plinko_drop_id' from 'transaction' table with index and foreign key.")

    op.drop_index(op.f('ix_plinko_drop_log_user_id'), table_name='plinko_drop_log')
    op.drop_index(op.f('ix_plinko_drop_log_timestamp'), table_name='plinko_drop_log')
    op.drop_table('plinko_drop_log')
    print("Dropped 'plinko_drop_log' table and its indexes.")
    # ### end Alembic commands ###
